# Structured Query Language (SQL)

### RECAP:

1. Pandas Apply
2. Pandas Groupby
3. Pandas Datatypes
4. Pandas Cleaning Strategies

#### SQL in python for data scientists

In this session we'll be using sqlite. In industries, most companies use mysql or postgresql (cloud solutions). The language and logic is similar.

SQL is a language designed to work with data

sqlite, mysql, etc are database systems that store data in a relational way

<img src="./images/sql.jpg" height=400, width=400>

With a lot more tables:

<img src="images/relational.png" height=400 width=400>

We use SQL because

1. It's an efficient data querying language
2. Industry standard
3. Scalable database system

for example: to find a row in a CSV file you need parse line by line, but in SQL it's index based so the look up time is exponentially quicker.

In [2]:
# If you havent so

!pip install pandas
!git clone https://github.com/christophersoo/bdss-ws2526.git

Requirement already satisfied: pandas in /usr/local/python/3.12.1/lib/python3.12/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from pandas) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python3 -m pip install --upgrade pip
Cloning into 'bdss-ws2526'...
remote: Enumerating objects: 298, done.
remote: Counting objects: 100% (102/102), done.
remote: Compressing objects: 100% (74/74), done.
remote: Total 298 (delta 58), reused 54 (delta 27), pack-reused 196 (from 1)
Receiving objects: 100% (298/298), 4.06 MiB | 28.11 MiB/s, done.
Resolving deltas: 100% (107/107), done.

In [3]:
import pandas as pd
import sqlite3

### Types of SQL query

1. DQL (Data Querying Language): Anything that reads data without permanently changing the database itself
2. DML (Data Manipulating Language): Anything that changes the data inside of tables and rows, but does not change internal structure like column names or column data types
3. DDL (Data Definition language): Anything that changes the structure of databases, such as the columns. This is also used to create new tables and remove tables in schemas.
4. DCL (Data Control Language): Acts as the authentication system to ensure the correct people are given the correct permissions to access correct databases
5. TCL (Transaction Control Language): A system to ensure robustness of manipulations in real production

As a data scientist, we'll mostly use SQL to extract information from a database, and manipulate them through pandas. This is the standard workflow. So this session will only focus on DQL

The basic syntax of DQL:

```{sql}
SELECT Columns, Expressions
FROM Tables, Joins
WHERE Condition
GROUP BY Column
HAVING Condition
ORDER BY Column
LIMIT number OFFSET number;
```

All of this is considered one query, you can do query to query operations like set operations, subqueries, CTEs, etc. But we won't cover that in this session

SQL parses this differently:

1. From: gathers the tables to create a single virtual table to query from
2. Where: initial filtering of rows
3. Group By: changes structure of virtual table
4. Having: filtering of rows based on group by
5. Select: filtering of columns and expressions on columns
6. Order By: sorting
7. Offset: skips first n rows
8. Limit: shows the first n rows

In [4]:
# setup a connection with the sqlite file
conn = sqlite3.connect("./bdss-ws2526/week3/data/chinook.sqlite")

# retrieves the cursor (allows us to write SQL)
cursor = conn.cursor()

# Executes the script to read table info in the file
cursor.execute("PRAGMA table_list;") 

# fetches result
result = cursor.fetchall() 

for table in result:
    print(f"table: {table[1]}")

table: Track
table: PlaylistTrack
table: Playlist
table: sqlite_schema
table: Artist
table: Customer
table: Employee
table: Genre
table: Invoice
table: Album
table: InvoiceLine
table: MediaType
table: sqlite_temp_schema

In [5]:
cursor.execute("SELECT * FROM Track LIMIT 2;")

result = cursor.fetchall()

result

[(1,
  'For Those About To Rock (We Salute You)',
  1,
  1,
  1,
  'Angus Young, Malcolm Young, Brian Johnson',
  343719,
  11170334,
  0.99),
 (2, 'Balls to the Wall', 2, 2, 1, None, 342562, 5510424, 0.99)]

Output looks messy, but we can actually use pandas to turn this into a dataframe!

In [22]:
df = pd.read_sql("SELECT * FROM InvoiceLine", conn) 
df.head(2)

   InvoiceLineId  InvoiceId  TrackId  UnitPrice  Quantity
0              1          1        2       0.99         1
1              2          1        4       0.99         1

### SQL: From

for the first one, we'll look at the FROM argument. FROM lets you gather multiple tables and create a virtual table to do the rest of your queries on.

The basic syntax is:

```{sql}
FROM table1 t1 INNER JOIN table2 t2 ON t1.id = t2.id
```

But you can even do more complicated nestings like:

```{sql}
FROM table1 t1 INNER JOIN table2 t2 ON t1.id = t2.id LEFT JOIN table3 t3 ON t2.name = t3.name
```

In [7]:
# Example

s1 = "Track t"
s2 = "Album a ON t.AlbumId = a.AlbumId"
s3 = "Artist b ON a.ArtistId = b.ArtistId"

df = pd.read_sql("SELECT t.Name, a.title, b.Name " \
f"FROM {s1} INNER JOIN {s2} INNER JOIN {s3}", conn) 

df

,Name,Title,Name
0,For Those About To Rock (We Salute You),For Those About To Rock We Salute You,AC/DC
1,Balls to the Wall,Balls to the Wall,Accept
2,Fast As a Shark,Restless and Wild,Accept
3,Restless and Wild,Restless and Wild,Accept
4,Princess of the Dawn,Restless and Wild,Accept
...,...,...,...
3498,Pini Di Roma (Pinien Von Rom) \ I Pini Della V...,Respighi:Pines of Rome,Eugene Ormandy
3499,"String Quartet No. 12 in C Minor, D. 703 ""Quar...",Schubert: The Late String Quartets & String Qu...,Emerson String Quartet
3500,"L'orfeo, Act 3, Sinfonia (Orchestra)",Monteverdi: L'Orfeo,"C. Monteverdi, Nigel Rogers - Chiaroscuro; Lon..."
3501,"Quintet for Horn, Violin, 2 Violas, and Cello ...",Mozart: Chamber Music,Nash Ensemble
3502,Koyaanisqatsi,Koyaanisqatsi (Soundtrack from the Motion Pict...,Philip Glass Ensemble

### SQL: SELECT

Next, we'll look at the SELECT argument. Select tells you how you want your output to look like before sorting, row filtering and offsetting.

The basic syntax is:

```{sql}
SELECT [DISTINCT] col, Expression
```

Here is DISTINCT is optional, if you add it you'll be getting distinct rows like pandas unique function

Expression here can be a lot of different types but the main ones are:

1. Arithmetic: col1 * col2
2. Aggregation: function(col1) -- collapses into one row, only for groupby
3. Cases: CASE WHEN condition THEN result ELSE result END AS col1
4. Window Functions: function(col1) OVER (PARTITION BY col ORDER BY col)

We won't get too much into window functions, and we will cover aggregation in group by

In [8]:
# Examples

s1 = "name"
s2 = "Bytes / Milliseconds AS byte_milli_ratio"
s3 = "CASE WHEN UnitPrice = 0 THEN 'free'" \
"WHEN UnitPrice > 1 THEN 'expensive' ELSE 'cheap'" \
"END AS cost_summary" 

df = pd.read_sql(f"SELECT {s1}, {s2}, {s3} FROM Track", conn) 

df

,Name,byte_milli_ratio,cost_summary
0,For Those About To Rock (We Salute You),32,cheap
1,Balls to the Wall,16,cheap
2,Fast As a Shark,17,cheap
3,Restless and Wild,17,cheap
4,Princess of the Dawn,16,cheap
...,...,...,...
3498,Pini Di Roma (Pinien Von Rom) \ I Pini Della V...,16,cheap
3499,"String Quartet No. 12 in C Minor, D. 703 ""Quar...",16,cheap
3500,"L'orfeo, Act 3, Sinfonia (Orchestra)",17,cheap
3501,"Quintet for Horn, Violin, 2 Violas, and Cello ...",16,cheap
3502,Koyaanisqatsi,16,cheap

### SQL: WHERE

Where is essentially an initial filtering (like boolean indexxing in pandas) right after FROM, so it's the first ever filter before select, group by, etc.

The syntax is simply:

```{sql}
WHERE condition
```

Here condition could be: col1 > 5 or col2 = "tree", etc

In [9]:
# Example:

df = pd.read_sql(f"SELECT name, UnitPrice FROM Track WHERE UnitPrice > 1", conn) 

df

                                       Name  UnitPrice
0    Battlestar Galactica: The Story So Far       1.99
1                    Occupation / Precipice       1.99
2                             Exodus, Pt. 1       1.99
3                             Exodus, Pt. 2       1.99
4                             Collaborators       1.99
..                                      ...        ...
208       There's No Place Like Home, Pt. 1       1.99
209       There's No Place Like Home, Pt. 2       1.99
210       There's No Place Like Home, Pt. 3       1.99
211                          Branch Closing       1.99
212                              The Return       1.99

[213 rows x 2 columns]

### SQL: GROUP BY

SQL group by has the same concept as pandas group by, essentially, you collapse the dataframe into another dataframe with its indexes as unique values of some target column, then every other value gets aggregated (collapsed into one value) for every other column with respect to their groups

Here's a python refresher:

In [10]:
df = pd.DataFrame({"age": [10, 11, 12, 9], "grade": [9, 8, 9, 6], "sex": ["M", "F", "F", "M"]})
df

   age  grade sex
0   10      9   M
1   11      8   F
2   12      9   F
3    9      6   M

In [11]:
def mean(col):
    return col.mean() 
    
def max(col):
    return col.max()


g = df.groupby("sex")
res = g.agg({"age": mean, "grade": max})

res

      age  grade
sex
F    11.5      9
M     9.5      9

In SQL, it would look like this:

```{sql}
SELECT sex, max(grade), avg(age)
FROM table
GROUP BY sex
```

In [12]:
# SQL Example

s1 = "GenreId"
s2 = "AVG(Milliseconds) AS avg_milli"
s3 = "MAX(Bytes) AS max_byte"

df = pd.read_sql(f"SELECT {s1}, {s2}, {s3} FROM Track GROUP BY {s1}", conn) 

df

    GenreId     avg_milli    max_byte
0         1  2.839100e+05    52490554
1         2  2.917554e+05    29416781
2         3  3.097494e+05    25966720
3         4  2.343538e+05    18139840
4         5  1.346435e+05     2616981
5         6  2.703598e+05    19161377
6         7  2.328593e+05    18092739
7         8  2.471778e+05    12086524
8         9  2.290341e+05    10564704
9        10  2.443709e+05    12727928
10       11  2.195900e+05    13490008
11       12  1.891642e+05     9541052
12       13  2.974529e+05    20670727
13       14  2.200669e+05    11477231
14       15  3.029858e+05    17582818
15       16  2.249238e+05     9632269
16       17  1.781763e+05    13559173
17       18  2.625549e+06   552893447
18       19  2.145041e+06  1054423946
19       20  2.911783e+06   587051735
20       21  2.575284e+06  1059546140
21       22  1.585264e+06   515301752
22       23  2.640585e+05    61118891
23       24  2.938676e+05    16454937
24       25  1.748130e+05     2861468

In general, the syntax looks like

```{sql}
SELECT target, agg(col1), agg(col2) ... 
FROM table
GROUP BY target
```

### SQL: HAVING

Having is very similar to where, but you filter over the newly formed dataframe (after the group by). Note that this comes after WHERE clause, so WHERE filters rows first, then you do group by then finally you use having to filter groups

In [13]:
# Example

s1 = "GenreId"
s2 = "AVG(Milliseconds) AS avg_milli"
s3 = "MAX(Bytes) AS max_byte"
s4 = "max_byte > 10000000"

df = pd.read_sql(f"SELECT {s1}, {s2}, {s3} FROM Track GROUP BY {s1} HAVING {s4}", conn) 

df

    GenreId     avg_milli    max_byte
0         1  2.839100e+05    52490554
1         2  2.917554e+05    29416781
2         3  3.097494e+05    25966720
3         4  2.343538e+05    18139840
4         6  2.703598e+05    19161377
5         7  2.328593e+05    18092739
6         8  2.471778e+05    12086524
7         9  2.290341e+05    10564704
8        10  2.443709e+05    12727928
9        11  2.195900e+05    13490008
10       13  2.974529e+05    20670727
11       14  2.200669e+05    11477231
12       15  3.029858e+05    17582818
13       17  1.781763e+05    13559173
14       18  2.625549e+06   552893447
15       19  2.145041e+06  1054423946
16       20  2.911783e+06   587051735
17       21  2.575284e+06  1059546140
18       22  1.585264e+06   515301752
19       23  2.640585e+05    61118891
20       24  2.938676e+05    16454937

### SQL: ORDER BY / LIMIT / OFFSET

Order by is essentially sorting in sql, it sorts the final table output based on some column, you can also select it based on ascending values or descending values.

Offset is essentially skipping rows, so if you do OFFSET n; that means skipping the first n rows

Limit is like pandas.head, where you limit the number of outputs you have. If you do limit n, then it only displays the first n rows, this naturally comes after order by and offset

We can use, offset, limit and order by to display the N-th largest value or any type of output we want after doing all the aggregation.

The basic syntax looks like:

```{sql}
SELECT col
FROM table
ORDER BY col [ASC / DESC]
LIMIT number OFFSET number;
```

In [14]:
# Example

query = "SELECT * FROM Track"

# This shows the 5-th smallest track in terms of bytes
df = pd.read_sql(f"{query} ORDER BY Bytes ASC LIMIT 1 OFFSET 4;", conn) 

df

,TrackId,Name,AlbumId,MediaTypeId,GenreId,Composer,Milliseconds,Bytes,UnitPrice
0,3304,Commercial 1,258,1,17,L. Muggerud,7941,319888,0.99

In [15]:
query = "SELECT * FROM Track"

# This shows the 2nd biggest track in terms of bytes
df = pd.read_sql(f"{query} ORDER BY Bytes DESC LIMIT 1 OFFSET 1;", conn) 

df

,TrackId,Name,AlbumId,MediaTypeId,GenreId,Composer,Milliseconds,Bytes,UnitPrice
0,2820,Occupation / Precipice,227,3,19,None,5286953,1054423946,1.99

## SQL PRACTICE

Task 1: write an sql query to print the first 10 rows of Employee table

In [18]:
# Your code here

df = pd.read_sql("SELECT * FROM Employee", conn)
df

,EmployeeId,LastName,FirstName,Title,ReportsTo,BirthDate,HireDate,Address,City,State,Country,PostalCode,Phone,Fax,Email
0,1,Adams,Andrew,General Manager,NaN,1962-02-18 00:00:00,2002-08-14 00:00:00,11120 Jasper Ave NW,Edmonton,AB,Canada,T5K 2N1,+1 (780) 428-9482,+1 (780) 428-3457,andrew@chinookcorp.com
1,2,Edwards,Nancy,Sales Manager,1.0,1958-12-08 00:00:00,2002-05-01 00:00:00,825 8 Ave SW,Calgary,AB,Canada,T2P 2T3,+1 (403) 262-3443,+1 (403) 262-3322,nancy@chinookcorp.com
2,3,Peacock,Jane,Sales Support Agent,2.0,1973-08-29 00:00:00,2002-04-01 00:00:00,1111 6 Ave SW,Calgary,AB,Canada,T2P 5M5,+1 (403) 262-3443,+1 (403) 262-6712,jane@chinookcorp.com
3,4,Park,Margaret,Sales Support Agent,2.0,1947-09-19 00:00:00,2003-05-03 00:00:00,683 10 Street SW,Calgary,AB,Canada,T2P 5G3,+1 (403) 263-4423,+1 (403) 263-4289,margaret@chinookcorp.com
4,5,Johnson,Steve,Sales Support Agent,2.0,1965-03-03 00:00:00,2003-10-17 00:00:00,7727B 41 Ave,Calgary,AB,Canada,T3B 1Y7,1 (780) 836-9987,1 (780) 836-9543,steve@chinookcorp.com
5,6,Mitchell,Michael,IT Manager,1.0,1973-07-01 00:00:00,2003-10-17 00:00:00,5827 Bowness Road NW,Calgary,AB,Canada,T3B 0C5,+1 (403) 246-9887,+1 (403) 246-9899,michael@chinookcorp.com
6,7,King,Robert,IT Staff,6.0,1970-05-29 00:00:00,2004-01-02 00:00:00,590 Columbia Boulevard West,Lethbridge,AB,Canada,T1K 5N8,+1 (403) 456-9986,+1 (403) 456-8485,robert@chinookcorp.com
7,8,Callahan,Laura,IT Staff,6.0,1968-01-09 00:00:00,2004-03-04 00:00:00,923 7 ST NW,Lethbridge,AB,Canada,T1H 1Y8,+1 (403) 467-3351,+1 (403) 467-8772,laura@chinookcorp.com

Task 2: Find all Employees that live in Canada and is an IT Staff

In [ ]:
# Your code here

Task 3: Give an output that has columns: EmployeeId, Address and BossAddress
where BossAddress is the address of the person the employee reports to

In [19]:
# Your code here

Task 4: Use SQL to create a group by dataframe for each country-state pair

Use python pandas to find the standard deviation of birth date and hire date and also classify the title based on the seniority (e.g support, staff, manager)

Return a dataframe that contains all these columns

In [ ]:
# Your code here

Task 5: Use SQL to query a table that consist of the genre and the customer location and the unitprice, you may use the customer, invoice, invoiceline, track and genre table for this. Use inner joins for all merging. 

For each genre-location pair, find the median, 0.25 quartile and 0.75 quartile values for the unit price. What can you say about your findings?

In [27]:
# Your code here